build_image: freedomjs/freedom
language: node_js
node_js:
- '0.10'
notifications:
  email:
    recipients:
      - uproxy-eng@googlegroups.com
    on_success: change
    on_failure: always
before_install:
  - "export DISPLAY=:10.0"
  - "Xvfb :10 -screen 0 1280x1024x24 &"
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - "google-chrome --version"
  - "firefox -v || echo 'No firefox installed.'"
  - "shippable_retry ./setup.sh install"
script:
  - "grunt test --firefox-bin /usr/bin/firefox"
env:
  secure: JJV9tXL7979J7L+TFJzu7bzZ+93rCka+kV1qhde48UWCUpndfmCp5TFkeboEbhtkTDT48+3ytMYqxLD/x21kiuU2GzRsCBbtu1FEt5fW1Ypk/HZVREgEhWyq0bedddAmsOEWjf8ZVxCnW+wTCeSSg4gwPjbM/ZE0+Y6Sc7PTWxaRkJLoFQ/DHAsg7DM4OBUJoiyXHZ2fOXJj/08M+DEwOr1ZyzgKH9nvqB1XirZ/aXO5hrF77tsg6Oz6YSWxgVaQqjhiRny2EhRQ5iQyoUIQ/sSE0nWYyLBc9TYs5hSlzt2rwaEFjJCL9u35DaXYfX2An5L5xuvHGvjfDMBkmnLwkw==
