build_image: dockerfile/chrome

language: node_js

node_js:
  - '0.10'

notifications:
  email:
    recipients:
      - uproxy-eng@googlegroups.com
    on_success: change
    on_failure: always

before_install:
  - npm install -g grunt-cli

install:
  - "shippable_retry ./setup.sh install"

before_script:
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"

script:
  - 'grunt integration_test'
